/Users/gerardomayor/Documents/estru_techos/apu_filter/procesador_csv.py:199: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_merged_apus["VR_UNITARIO_INSUMO"].fillna(0, inplace=True)
/Users/gerardomayor/Documents/estru_techos/apu_filter/procesador_csv.py:213: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final["VR_UNITARIO_CALCULADO"].fillna(0, inplace=True)
/Users/gerardomayor/Documents/estru_techos/apu_filter/procesador_csv.py:214: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final["CANTIDAD_PRESUPUESTO"].fillna(0, inplace=True)
F
======================================================================
FAIL: test_process_all_files_structure_and_calculations (__main__.TestCSVProcessor.test_process_all_files_structure_and_calculations)
Prueba la funci√≥n orquestadora `process_all_files`, verificando tanto
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gerardomayor/Documents/estru_techos/apu_filter/test_app.py", line 88, in test_process_all_files_structure_and_calculations
    self.assertEqual(len(presupuesto_procesado), 2)
AssertionError: 3 != 2

----------------------------------------------------------------------
Ran 1 test in 0.290s

FAILED (failures=1)